# Generated by Django 4.2.28 on 2026-03-11 14:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.IntegerField(help_text='Original row index inside the shapefile.')),
                ('properties', models.JSONField(blank=True, default=dict, help_text='All non-geometry attributes from the shapefile row.')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(help_text='Geometry in WGS-84. Queryable with ST_Within, ST_Intersects, ST_Buffer, etc.', srid=4326)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_session', models.ForeignKey(help_text='The upload session this feature belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='geo.uploadsession')),
            ],
            options={
                'ordering': ['upload_session', 'feature_index'],
                'indexes': [models.Index(fields=['upload_session', 'feature_index'], name='geo_uploade_upload__212522_idx')],
            },
        ),
    ]
