# Generated by Django 4.2.28 on 2026-03-11 18:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analysissession_filename_and_more'),
        ('geo', '0002_uploadedfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.IntegerField(help_text='Original row index from the uploaded shapefile.')),
                ('classification', models.CharField(choices=[('unchanged', 'Unchanged'), ('modified', 'Modified'), ('removed', 'Removed'), ('new', 'New'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='Classification confidence score (0-1).', null=True)),
                ('iou_score', models.FloatField(blank=True, help_text='IoU between input polygon and SAM-detected polygon.', null=True)),
                ('pixel_score', models.FloatField(blank=True, help_text='Pixel-based building presence score.', null=True)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Original shapefile attributes + classification metadata.')),
                ('input_geom', django.contrib.gis.db.models.fields.GeometryField(help_text='Original building footprint from shapefile.', srid=4326)),
                ('detected_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='SAM-detected building footprint (may differ from input).', null=True, srid=4326)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classified_buildings', to='api.analysissession')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_buildings', to='geo.uploadsession')),
            ],
            options={
                'ordering': ['upload_session', 'feature_index'],
                'indexes': [models.Index(fields=['upload_session', 'classification'], name='geo_classif_upload__56f98d_idx'), models.Index(fields=['analysis_session', 'classification'], name='geo_classif_analysi_291b7f_idx')],
            },
        ),
    ]
