# Generated by Django 4.2.28 on 2026-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
